name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TENANCY_CENTRAL_CONNECTION: sqlite
      TENANCY_CENTRAL_DOMAINS: '127.0.0.1,localhost'
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo_mysql, sqlite3, pdo_sqlite
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-scripts

      - name: Run tests
        run: vendor/bin/phpunit --testdox
